### ISSUE TITLE
IPv6 CloudFront Address being added

### ISSUE THREAD

**Issue by daniellwm** [aws-samples/aws-cloudfront-samples#10]
From latest ip-ranges.json, CloudFront staring to have IPv6 address appear under ipv6_prefixes section as below

    {
      "ipv6_prefix": "2600:9000::/28",
      "region": "GLOBAL",
      "service": "CLOUDFRONT"
    }

it's time to add ipv6_prefixes range also

**Comment by brianwthomas** [comment]
Is there a need for IPv6 since CloudFront only connects to the origin over IPv4?

**Comment by baldwinmatt** [comment]
CloudFront does not support origin fetched over ipv6 at this time.  Closing.
