### ISSUE TITLE
Default 'AutoUpdate' TAG name needs changing

### ISSUE THREAD

**Issue by mikejamesowen** [aws-samples/aws-cloudfront-samples#23]
Just tested this and it looks to me like line 28:
'AutoUpdate': os.environ.get('TagAutoUpdate', 'AutoUpdateTag'),

Needs changing to:
'AutoUpdate': os.environ.get('TagAutoUpdate', 'AutoUpdate'),

As then it works as per:
https://aws.amazon.com/blogs/security/how-to-automatically-update-your-security-groups-for-amazon-cloudfront-and-aws-waf-by-using-aws-lambda/

....apart from the fact that the article above mentions Python 2.7, and not 3.7, which is required.

**Comment by colmobrien84** [comment]
experienced same ^^^

**Comment by rabee77** [comment]
Experienced the same issue as well, please correct the function.

in the documentation it recommends to use Python 2.7 which is incorrect.

**Comment by mprenditore** [comment]
Just wasted 4 hours to find it out.

**Comment by ryanall** [comment]
Got caught by the same issue today!
https://github.com/aws-samples/aws-cloudfront-samples/pull/26

**Comment by baldwinmatt** [comment]
Resolved
