### ISSUE TITLE
Python 2.7 end of support

### ISSUE THREAD

**Issue by saifeer** [aws-samples/aws-cloudfront-samples#25]
The Python language governing body – Python Software Foundation (PSF) – will end support for Python 2.7 on January 1, 2020. Amazon is encouraging users to upgrade to Python 3 as a result of this.

Can this sample be upgraded to use Python 3 soon please?

**Comment by spedicino** [comment]
Hi Saifeer,
Actually I think the documentation is out of date, but the code is actually working with python 3.6 runtime.

I felt the same way at first, but when I selected python 2.7 as the runtime, I was getting a few weird error messages. I changed it to python 3.7 and all those error messages went away!

Give it a try, and let us know how it went!

Cheers,
Sergio

**Comment by rarylson** [comment]
Hi guys,

The blog post that refers to this project was updated: https://aws.amazon.com/blogs/security/how-to-automatically-update-your-security-groups-for-amazon-cloudfront-and-aws-waf-by-using-aws-lambda/

> Note from December 3, 2019: The features and services described in this post have changed since the post was published and the procedures described might be out of date and no longer accurate. If we update this post or create a replacement, we’ll add a notification about it here.

The current code (latest commit in the master branch) is already using Python 3.
