### ISSUE TITLE
More Ranges than allowed rules per Security Group

### ISSUE THREAD

**Issue by wyattconsulting** [aws-samples/aws-cloudfront-samples#27]
`jq -r '.prefixes[] | select(.service=="CLOUDFRONT") | .ip_prefix' < ip-ranges.json |wc -l`

returns 67 IP ranges

The rule limit per security group is 50. This sample needs updated to make use of multiple security groups. 

I will work on a pull request, just wanted to make sure you knew.

**Comment by marcelofernandez** [comment]
But this script adds rules in 2 different SGs, one for "GLOBAL" CloudFront IPs and another one for "REGION" IP addresses. If you count them separately, you get up to 35 rules.

Today, there are 35 rules:
`jq -r '.prefixes[] | select(.service=="CLOUDFRONT") | select(.region=="GLOBAL") | .ip_prefix' < ip-ranges.json | wc -l`

and 33 regional rules:
`jq -r '.prefixes[] | select(.service=="CLOUDFRONT") | select(.region!="GLOBAL") | .ip_prefix' < ip-ranges.json | wc -l`

Are you sure this script generates more than 50 rules in one SG?

Regards
