### ISSUE TITLE
Nearly reaching the max rule limit of 40 rules

### ISSUE THREAD

**Issue by sfgeorge** [aws-samples/aws-cloudfront-samples#8]
_First, thank you for this very helpful lambda!_

Second, just wanted to share this as just a warning bell for the future.  At the time of this posting, https://ip-ranges.amazonaws.com/ip-ranges.json includes ~34~ 39 distinct "CLOUDFRONT" i.p. ranges. 
 However, AWS only permits up to 40 i.p. ranges to be added to a single security group.

If a time comes when AWS publishes > 40 i.p. ranges for CloudFront, then this lambda will fail with something like this:

> sg-abcd1234: Adding 1.2.255.128/26:80
>
> sg-abcd1234: Adding 1.3.255.128/26:80
>
> An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation: The maximum number of rules per security group has been reached.: ClientError

If that happens, we may need to not just create 2 security groups for http and https, but a few more, in order to distribute the growing list.

I don't know the rate at which the ip ranges tend to be added to CloudFront, so it's possible this may not be an eminent threat whatsoever.

**Comment by ShakataGaNai** [comment]
So I'm trying to deploy this script for the first time today and ran across the error mentioned. The ip-ranges.json file is now up to 39 CLOUDFRONT ranges. If you use the "out-of-the-box" solution assuming both (which I did) HTTP and HTTPS, this will definitely fail. If you have any sort of "out-of-the-box" default rules (or custom rules in addition to CF, ex drop ICMP), this will fail.  

Here's my lambda output just for the record:

```
2.191.128/26:80
sg-xxx123xxx: Adding 52.56.127.0/25:80
sg-xxx123xxx: Adding 52.57.254.0/24:80
sg-xxx123xxx: Adding 52.66.194.128/26:80
sg-xxx123xxx: Adding 52.78.247.128/26:80
sg-xxx123xxx: Adding 52.84.0.0/15:80
sg-xxx123xxx: Adding 52.199.127.192/26:80
sg-xxx123xxx: Adding 52.212.248.0/26:80
sg-xxx123xxx: Adding 52.220.191.0/26:80
sg-xxx123xxx: Adding 52.222.128.0/17:80
sg-xxx123xxx: Adding 54.182.0.0/16:80
sg-xxx123xxx: Adding 54.192.0.0/16:80
sg-xxx123xxx: Adding 54.230.0.0/16:80
sg-xxx123xxx: Adding 54.233.255.128/26:80
sg-xxx123xxx: Adding 54.239.128.0/18:80
sg-xxx123xxx: Adding 54.239.192.0/19:80
sg-xxx123xxx: Adding 54.240.128.0/18:80
sg-xxx123xxx: Adding 204.246.164.0/22:80
sg-xxx123xxx: Adding 204.246.168.0/22:80
sg-xxx123xxx: Adding 204.246.174.0/23:80
sg-xxx123xxx: Adding 204.246.176.0/20:80
sg-xxx123xxx: Adding 205.251.192.0/19:80
sg-xxx123xxx: Adding 205.251.249.0/24:80
sg-xxx123xxx: Adding 205.251.250.0/23:80
sg-xxx123xxx: Adding 205.251.252.0/23:80
sg-xxx123xxx: Adding 205.251.254.0/24:80
sg-xxx123xxx: Adding 216.137.32.0/19:80
sg-xxx123xxx: Added 39, Revoked 1
sg-xxx123xxx: Revoking 0.0.0.0/0:443
sg-xxx123xxx: Adding 13.32.0.0/15:443
sg-xxx123xxx: Adding 13.54.63.128/26:443
sg-xxx123xxx: Adding 13.59.250.0/26:443
sg-xxx123xxx: Adding 13.113.203.0/24:443
sg-xxx123xxx: Adding 13.228.69.0/24:443
sg-xxx123xxx: Adding 34.195.252.0/24:443
sg-xxx123xxx: Adding 34.226.14.0/24:443
sg-xxx123xxx: Adding 35.158.136.0/24:443
sg-xxx123xxx: Adding 35.162.63.192/26:443
sg-xxx123xxx: Adding 35.167.191.128/26:443
sg-xxx123xxx: Adding 52.15.127.128/26:443
sg-xxx123xxx: Adding 52.46.0.0/18:443
sg-xxx123xxx: Adding 52.52.191.128/26:443
sg-xxx123xxx: Adding 52.56.127.0/25:443
sg-xxx123xxx: Adding 52.57.254.0/24:443
sg-xxx123xxx: Adding 52.66.194.128/26:443
sg-xxx123xxx: Adding 52.78.247.128/26:443
sg-xxx123xxx: Adding 52.84.0.0/15:443
sg-xxx123xxx: Adding 52.199.127.192/26:443
sg-xxx123xxx: Adding 52.212.248.0/26:443
sg-xxx123xxx: Adding 52.220.191.0/26:443
sg-xxx123xxx: Adding 52.222.128.0/17:443
sg-xxx123xxx: Adding 54.182.0.0/16:443
sg-xxx123xxx: Adding 54.192.0.0/16:443
sg-xxx123xxx: Adding 54.230.0.0/16:443
sg-xxx123xxx: Adding 54.233.255.128/26:443
sg-xxx123xxx: Adding 54.239.128.0/18:443
sg-xxx123xxx: Adding 54.239.192.0/19:443
sg-xxx123xxx: Adding 54.240.128.0/18:443
sg-xxx123xxx: Adding 204.246.164.0/22:443
sg-xxx123xxx: Adding 204.246.168.0/22:443
sg-xxx123xxx: Adding 204.246.174.0/23:443
sg-xxx123xxx: Adding 204.246.176.0/20:443
sg-xxx123xxx: Adding 205.251.192.0/19:443
sg-xxx123xxx: Adding 205.251.249.0/24:443
sg-xxx123xxx: Adding 205.251.250.0/23:443
sg-xxx123xxx: Adding 205.251.252.0/23:443
sg-xxx123xxx: Adding 205.251.254.0/24:443
sg-xxx123xxx: Adding 216.137.32.0/19:443
An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation: The maximum number of rules per security group has been reached.: ClientError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 36, in lambda_handler
    result = update_security_groups(cf_ranges)
  File "/var/task/lambda_function.py", line 77, in update_security_groups
    if update_security_group(client, group, new_ranges, INGRESS_PORTS['Https']):
  File "/var/task/lambda_function.py", line 109, in update_security_group
    added += add_permissions(client, group, permission, to_add)
  File "/var/task/lambda_function.py", line 143, in add_permissions
    client.authorize_security_group_ingress(GroupId=group['GroupId'], IpPermissions=[add_params])
  File "/var/runtime/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation: The maximum number of rules per security group has been reached.

```

**Comment by sfgeorge** [comment]
Thank you @ShakataGaNai, especially helpful to know that it's up to 39 ip ranges now.  Yikes, dangerously close to the limit of 40!

This seems like a good time to begin discussing how to address the problem.

Here's a suggestion from me... please comment and critique, I'd like other opinions on this...

#### Problem

As you know, the current lambda collects any groups you have designated for all of the http rules as well https rules, based on finding security groups that have 3 tags in common:

   SECURITY_GROUP_TAG_FOR_HTTP = { 'Name': 'cloudfront', 'AutoUpdate': 'true', 'Protocol': 'http' }
   SECURITY_GROUP_TAG_FOR_HTTPS = { 'Name': 'cloudfront', 'AutoUpdate': 'true', 'Protocol': 'https' }

This model assumes that each group found will be able to contain a rule for _each_ ip range associated with CloudFront, which is becoming too presumptuous.

#### Group collections with rule shard-ing

Proposed:  Allow the existing `SECURITY_GROUP_TAG_FOR_HTTP` and `SECURITY_GROUP_TAG_FOR_HTTPS` collections to behave as they currently do. Meanwhile allow users to specify Collection(s) of security groups, with each Collection to contain the entire set of ip ranges sharded amongst however many security groups have the same "CollectionName" in common.

##### Rule Sharding Security Group Configuration

To utilize rule sharding, you would add a few new security groups that each must have the following tags:

Tag  | Value
---- | -----
Name       | cloudfront
AutoUpdate | true
CollectionName | _\<CollectionName\>_ \*\*
Ports | _\<Ports\>_ \*\*\*

\*\* First, you must come up with a "CollectionName".  Then, you must create multiple security groups that have a common value for the CollectionName tag.

\*\*\* Next, you must add a "Ports" tag to each security group of each collection, defining the port(s) that you want to accept from CloudFront as a comma-separated list.  The most typical settings would be `Ports: "80"`, `Ports: "443"` or `Ports: "80,443"`.

##### Example

Imagine you defined the following new security groups:

Group Name | Tags
---------- | -------------
http_1     | `CollectionName: insecure_landing`, `Ports: 80`, `Name: cloudfront`, `AutoUpdate: true`
http_2     | `CollectionName: insecure_landing`, `Ports: 80`, `Name: cloudfront`, `AutoUpdate: true`
https_1    | `CollectionName: corporate_portal`, `Ports: 443`, `Name: cloudfront`, `AutoUpdate: true`
https_2    | `CollectionName: corporate_portal`, `Ports: 443`, `Name: cloudfront`, `AutoUpdate: true`
omni_1     | `CollectionName: ecom`, `Ports: 80,443`, `Name: cloudfront`, `AutoUpdate: true`
omni_2     | `CollectionName: ecom`, `Ports: 80,443`, `Name: cloudfront`, `AutoUpdate: true`
omni_3     | `CollectionName: ecom`, `Ports: 80,443`, `Name: cloudfront`, `AutoUpdate: true`

Now presume that https://ip-ranges.amazonaws.com/ip-ranges.json included _50_ ip ranges defined for "CLOUDFRONT".  How would the above security groups behave?

1. The "insecure_landing" Collection, comprised of groups http_1 and http_2, would need a total 50 rules allowing inbound port 80 traffic only.  Those 50 rules would be divided amongst the number of shards (2 in this case), putting 25 rules into http_1 and 25 rules into http_2.
2. The "corporate_portal" Collection, comprised of groups https_1 and https_2, would need a total of 50 rules allowing inbound port 443 traffic only.  Those 50 rules would be divided amongst the number of shards (2 in this case), putting 25 rules into https_1 and 25 rules into https_2.
3. The "ecom" Collection, comprised of groups omni_1, omni_2 and omni_3, would need 50 rules allowing inbound port 80 traffic _PLUS_ 50 rules of inbound port 443 traffic.  Those 100 rules would be divided amongst the number of shards (3 in this case), putting roughly 34 rules into omni_1, 33 rules into omni_2 and 33 rules into omni_3.

##### Proactive Warning

Additionally, any time the lambda detects that a Shard-enabled security group has 30 or more rules in it, it will log a CloudWatch warning like the following:

> WARNING: Security Group \<Group Name\> contains \<number-of-rules\> out of 40 rules.  Add more security groups with CollectionName \<CollectionName\>.

##### Questions/Thoughts
* In addition to a logging potential the *Proactive Warning* above to CloudWatch, should we create a metric or SNS alarm that would tell the user of the problem?  What's the best way of doing this without incurring much cost to the user?

**Comment by jaydp17** [comment]
Facing the same, issue 😕

**Comment by mateusz** [comment]
Hey, just cruising the internet looking for ways people deal with security group rule limits. So far nothing, but did you know you can ask AWS to increase your rule-per-sg limit at a cost of sgs-per-eni? The hard limit is 250 rules per eni per vpc apparently.

**Comment by nalinguptalinux** [comment]
+1

**Comment by popsieandal** [comment]
Hello, 

I Tried to test the Lamda function and i got this error:

Response:
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      29,
      "lambda_handler",
      "result = update_security_groups(ip_ranges)"
    ],
    [
      "/var/task/lambda_function.py",
      77,
      "update_security_groups",
      "if update_security_group(client, group, new_ranges[\"GLOBAL\"], INGRESS_PORTS['Http']):"
    ],
    [
      "/var/task/lambda_function.py",
      106,
      "update_security_group",
      "if permission['FromPort'] <= port and permission['ToPort'] >= port :"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'FromPort'"
}

Request ID:
"b28f20f4-7819-11e8-90d1-df2a8fa3d1e6"

Function Logs:
\"md5\": \"3656462fc05579ada8c3a11f17a1f0d7\", \"url\": \"https://ip-ranges.amazonaws.com/ip-ranges.json\"}", 
        "Type": "Notification", 
        "UnsubscribeUrl": "EXAMPLE", 
        "TopicArn": "arn:aws:sns:EXAMPLE", 
        "Subject": "TestInvoke"
      }
    }
  ]
}
Updating from https://ip-ranges.amazonaws.com/ip-ranges.json
Found CLOUDFRONT region: GLOBAL range: 13.32.0.0/15
Found CLOUDFRONT region: GLOBAL range: 13.35.0.0/16
Found CLOUDFRONT region: GLOBAL range: 52.46.0.0/18
Found CLOUDFRONT region: GLOBAL range: 52.84.0.0/15
Found CLOUDFRONT region: GLOBAL range: 52.124.128.0/17
Found CLOUDFRONT region: GLOBAL range: 52.222.128.0/17
Found CLOUDFRONT region: GLOBAL range: 54.182.0.0/16
Found CLOUDFRONT region: GLOBAL range: 54.192.0.0/16
Found CLOUDFRONT region: GLOBAL range: 54.230.0.0/16
Found CLOUDFRONT region: GLOBAL range: 54.239.128.0/18
Found CLOUDFRONT region: GLOBAL range: 54.239.192.0/19
Found CLOUDFRONT region: GLOBAL range: 54.240.128.0/18
Found CLOUDFRONT region: GLOBAL range: 64.252.64.0/18
Found CLOUDFRONT region: GLOBAL range: 70.132.0.0/18
Found CLOUDFRONT region: GLOBAL range: 71.152.0.0/17
Found CLOUDFRONT region: GLOBAL range: 143.204.0.0/16
Found CLOUDFRONT region: GLOBAL range: 204.246.164.0/22
Found CLOUDFRONT region: GLOBAL range: 204.246.168.0/22
Found CLOUDFRONT region: GLOBAL range: 204.246.174.0/23
Found CLOUDFRONT region: GLOBAL range: 204.246.176.0/20
Found CLOUDFRONT region: GLOBAL range: 205.251.192.0/19
Found CLOUDFRONT region: GLOBAL range: 205.251.249.0/24
Found CLOUDFRONT region: GLOBAL range: 205.251.250.0/23
Found CLOUDFRONT region: GLOBAL range: 205.251.252.0/23
Found CLOUDFRONT region: GLOBAL range: 205.251.254.0/24
Found CLOUDFRONT region: GLOBAL range: 216.137.32.0/19
Found CLOUDFRONT region: ap-southeast-2 range: 13.54.63.128/26
Found CLOUDFRONT region: us-east-2 range: 13.59.250.0/26
Found CLOUDFRONT region: ap-northeast-1 range: 13.113.203.0/24
Found CLOUDFRONT region: ap-northeast-2 range: 13.124.199.0/24
Found CLOUDFRONT region: ap-southeast-1 range: 13.228.69.0/24
Found CLOUDFRONT region: us-east-2 range: 18.216.170.128/25
Found CLOUDFRONT region: us-east-1 range: 34.195.252.0/24
Found CLOUDFRONT region: us-west-2 range: 34.216.51.0/25
Found CLOUDFRONT region: us-east-1 range: 34.226.14.0/24
Found CLOUDFRONT region: us-east-1 range: 34.232.163.208/29
Found CLOUDFRONT region: eu-central-1 range: 35.158.136.0/24
Found CLOUDFRONT region: us-west-2 range: 35.162.63.192/26
Found CLOUDFRONT region: us-west-2 range: 35.167.191.128/26
Found CLOUDFRONT region: us-east-2 range: 52.15.127.128/26
Found CLOUDFRONT region: eu-west-3 range: 52.47.139.0/24
Found CLOUDFRONT region: us-west-1 range: 52.52.191.128/26
Found CLOUDFRONT region: eu-west-2 range: 52.56.127.0/25
Found CLOUDFRONT region: eu-central-1 range: 52.57.254.0/24
Found CLOUDFRONT region: ap-south-1 range: 52.66.194.128/26
Found CLOUDFRONT region: ap-northeast-2 range: 52.78.247.128/26
Found CLOUDFRONT region: ap-northeast-1 range: 52.199.127.192/26
Found CLOUDFRONT region: eu-west-1 range: 52.212.248.0/26
Found CLOUDFRONT region: ap-southeast-1 range: 52.220.191.0/26
Found CLOUDFRONT region: sa-east-1 range: 54.233.255.128/26
Found 1 CloudFront_g HttpSecurityGroups to update
Found 1 CloudFront_g HttpsSecurityGroups to update
Found 1 CloudFront_r HttpSecurityGroups to update
Found 1 CloudFront_r HttpsSecurityGroups to update
'FromPort': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 29, in lambda_handler
    result = update_security_groups(ip_ranges)
  File "/var/task/lambda_function.py", line 77, in update_security_groups
    if update_security_group(client, group, new_ranges["GLOBAL"], INGRESS_PORTS['Http']):
  File "/var/task/lambda_function.py", line 106, in update_security_group
    if permission['FromPort'] <= port and permission['ToPort'] >= port :
KeyError: 'FromPort'

END RequestId: b28f20f4-7819-11e8-90d1-df2a8fa3d1e6
REPORT RequestId: b28f20f4-7819-11e8-90d1-df2a8fa3d1e6	Duration: 892.66 ms	Billed Duration: 900 ms 	Memory Size: 128 MB	Max Memory Used: 46 MB

**Comment by leofernandezg** [comment]
+1
I want to use a modification of this script to update the Outbound rules to us-east-1 AMAZON IPs. (are more than 50).

**Comment by albogdano** [comment]
@popsieandal The solution to the `'FromPort': KeyError` is to add this conditional statement on line 119:
```python
if 'FromPort' in permission :
```

**Comment by ecout** [comment]
Guess what? It's here....wohoooo!!! FIX IT darn it! It's been over 2 years...2 years!!
I didn't even use the lambda I just wrote my own Ansible script and got this...

Unable to authorize in for ip 52.124.128.0/17 security group 'xxxxxxx' - An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation

**Comment by ssm-alex** [comment]
@ecout, I hope you realize that:

A) The code was updated a year ago to break up the CloudFront entries between Global and Regional.  Right now there are 35 Global entries and 26 Regional Entries, broken up into 4 Security Groups if you wanted both HTTP and HTTPS traffic.  You could look at the reference script as a basis to modify your Ansible one

and

B) You can put in a limit request to change your default number of 60 entries per SG (AWS silently upgraded this limit from 50) and 5 SG per Network Interface.  More details: https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups

> Guess what? It's here....wohoooo!!! FIX IT darn it! It's been over 2 years...2 years!!
> I didn't even use the lambda I just wrote my own Ansible script and got this...
> 
> Unable to authorize in for ip 52.124.128.0/17 security group 'xxxxxxx' - An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation
> 
> So now I have to write a parser and break the lists down into multiple lists of 40 items each and then iterate to create a list of SGs then assign that to the ELB and we all love extra-non productive work...
> 
> So what's the pattern to allow traffic from cloudfront only then?

**Comment by ecout** [comment]
> ear ago to break up the CloudFront entries between Global and Regional. Right now there are 35 Global entries and 26 Regional Entries, broken up into 4 Security Groups if you wanted both HTTP and HTTPS traffic. You could look at the reference script as a basis to modify your Ansible one

Actually I just came back to edit my post because I just realized that. So yes, I'm creating two separate Security groups for the counter. Thanks!

**Comment by Sneakr** [comment]
Well, not I have reache 60 and it gives the error. Seems like we cant rely on a hard limit.

**Comment by rarylson** [comment]
This issue is very similar to #11.

But here in this thread we have some good insights about a more generic approach (the `CollectionName` tag idea).

The current implementation (commit 340f9d) breaks the rules in four different SGs: Global/HTTP, Global/HTTPS, Regional/HTTP, Regional/HTTPS. This will work for a while.

I did a test today, and I got the following results:

```console
$ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region == "GLOBAL")) | length'
36

$ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region != "GLOBAL")) | length'
31
```

It is, it's expected to have 36 rules in the SG `cloudfront_g`, and 31 rules in the SG `cloudfront_r`.

So, I've tested the lambda function, and everything worked well.

I guess the "aws-cloudfront-samples" owners could close this issue now.

**Comment by baldwinmatt** [comment]
Resolved

**Comment by dan0mau** [comment]
There are now 64 GLOBAL and it's broken again!

**Comment by joeltay17** [comment]
same here. i need to split into more SGs now.

**Comment by Binternet** [comment]
Broke again, now its even higher:

```
➜  ~ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region == "GLOBAL")) | length'
71
➜  ~ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region != "GLOBAL")) | length'
48
```
